### ISSUE TITLE
Workload Krügergraph should show real data

### ISSUE THREAD

**Issue by fabianhe** [hyrise/Cockpit#183]
**Is your feature request related to a problem? Please describe.**
The data for the workload Krügergraph is mocked.

**Describe the solution you'd like**
It should be real data.

**Affected Component**
`Cockpit Backend`, `WorkloadGenerator`

**Comment by PeterTsayun** [comment]
As far as I know, Hyrise offers an endpoint for the number of scans/joins/aggregations, which were executed in the past seconds. We could show this data in Krügergraph. It could be more interesting, than type of the queries (`SELECT`, `DELETE` ...), because absolute majority of the queries are currently of the `SELECT`-type.

**Comment by fabianhe** [comment]
Where can I find this endpoint?

**Comment by Bouncner** [comment]
There are means in Hyrise that allow us to provide the requested information "rather easily", but they are currently not fed into any meta tables. Thus, there is no endpoint yet.

**Comment by cH3n7i** [comment]
> Thus, there is no endpoint yet.

Halting the issue for now, waiting for the Hyrise endpoint

**Comment by Bouncner** [comment]
One issue has just been closed. Was this ticket only the endpoint ticket (it did not sound so)?

If not, is this ticket here done?

**Comment by PeterTsayun** [comment]
> Was this ticket only the endpoint ticket (it did not sound so)?

It was the issue of implementing the corresponding endpoint in the backend for providing the operator data (which will be used for Krueger graph 2.0). We'll create a separate issue for the frontend.

Do we want to keep the old version of the Kruegergraph as well, for visualizing the types of queries? Like SELECT, UPDATE, DELETE, etc (which is currently mocked).
