### ISSUE TITLE
Backend API response times can be bad

### ISSUE THREAD

**Issue by fabianhe** [hyrise/Cockpit#225]
**Is your feature request related to a problem? Please describe:**  
Response times from the `Cockpit Backend` vary and can be quite bad sometimes. This may be due to running in a single thread:

https://github.com/hyrise/Cockpit/blob/7465c6058825192d2de56d35fdc2fc0550ba4c80/hyrisecockpit/backend/cli.py#L9

**Please describe the solution you'd like:**  
Run multi-threaded.

**Please describe alternatives you've considered:**  
None, up for discussion.

**Affected Component(s):**  
`Cockpit Backend`

**Additional context:**  
Single threaded mode has been introduced due to some issues with `zmq`. This will have to be resolved.

**Comment by cH3n7i** [comment]
Response times improved, closed for now.
