### ISSUE TITLE
Show request interval in access map

### ISSUE THREAD

**Issue by MaxSchneider1337** [hyrise/Cockpit#411]
**Is your feature request related to a problem? Please describe:**  
The user does not know how often the accessmap data is fetched. 

**Please describe the solution you'd like:**  
Show the interval in the card (use the whitespace)

**Please describe alternatives you've considered:**  
could also be shown on element-hover, but this seems to be much harder and hard to find for the user

**Affected Component(s):**  
frontend

**Comment by schTi** [comment]
To be consistent, we should do this for all data, which is not shown in a line chart
