### ISSUE TITLE
change color for heatmap

### ISSUE THREAD

**Issue by monasobh** [hyrise/Cockpit#413]
**Is your feature request related to a problem? Please describe:**  
The white color of the heatmap ist not good to indicate 0 access because it seems as if there is no data. 

**Please describe the solution you'd like:**  
Change the white color for 0-access to bright grey. 

**Affected Component(s):**  
`Frontend`

**Comment by MaxSchneider1337** [comment]
have you tried some colors. Yellow, for example, could also look kind of good
