### ISSUE TITLE
Backend endpoint to execute queries directly

### ISSUE THREAD

**Issue by fabianhe** [hyrise/Cockpit#428]
**Is your feature request related to a problem? Please describe:**  
Executing queries directly could improve the usability of the Cockpit.

**Please describe the solution you'd like:**  
An endpoint to execute queries directly. They will be executed on a single database, and not be multiplexed to all databases like e.g. workload queries.
Ideally, direct execution would mean no enqueueing, but long-running queries could make this rather unresponsive.

**Please describe alternatives you've considered:**  
None.

**Affected Component(s):**  
`CockpitBackend`, `DatabaseManager`

**Comment by Bensk1** [comment]
Correct, these should only be executed on a single database, @fabianhe. We do not want to get into analyzing whether these queries are going to be expensive or not, this should be the user's responsibility. If the user is brave enough to send direct database commands, she should take the responsibility.

**Comment by fabianhe** [comment]
@Bensk1 Yes, I didn't mean to steer this towards runtime query analysis. The possibility of expensive queries, however, would shape implementation details.

Currently, we're thinking about two ways of implementing it:
1) Forwarding the query: Frontend -> `FlaskBackend` -> `DatabaseManager` -> `Database` -> Hyrise
  (and in reverse for the result)
2) Same as above, but enqueueing the query at the `Database`, thus either dropping the result or storing the result somewhere else for retrieval. The `Database` would return a promise to execute the query.

As I see it, 1) would be the expected behavior, but if one would execute a query that runs for a minute, it would block the currently single-threaded backend at the `FlaskBackend`, `DatabaseManager`, and `Database` level. Therefore, even a multithreaded `FlaskBackend` would not solve this.

**Comment by Bensk1** [comment]
If this blocks the complete backend (even if it's for less than a second), this should not be the way to go.
