### ISSUE TITLE
Provide encoding distribution

### ISSUE THREAD

**Issue by PeterTsayun** [hyrise/Cockpit#429]
**Is your feature request related to a problem? Please describe:**  
For now, we return the encoding type of columns in `/storage` data as a list. In the future, we should be able to see the distribution of the encoding, i. e. how many percents of the column is encoded with what type. This information should then be shown in the treemap in frontend.

**Please describe the solution you'd like:**  
Instead of list of string, representing encoding, we could return a list with objects in `/storage`. In each object, there is a key for the name of the encoding and for its percent number, like:
```
[
  {
    "encoding": "Dictionary",
    "percent": 34.6
  },
  ...
]
```

**Please describe alternatives you've considered:**  
Any alternatives are welcome.

**Affected Component(s):**  
`BackgroundScheduler`

**Additional context:**

**Comment by Bensk1** [comment]
Duplicate/overlap with #436

**Comment by cH3n7i** [comment]
duplicate
