### ISSUE TITLE
Reload required to get correct state of plugins

### ISSUE THREAD

**Issue by cH3n7i** [hyrise/Cockpit#431]
**Please describe the bug:**  
After loading a Plugin to a database, you need to refresh the frontend in order to get the correct state.

**Please describe steps to reproduce:**  
1. Connect a database
2. Activate a plugin
3. See error

**What is the expected behavior? Please describe:**  
The current state and information should be shown without the necessary reload.

**Affected Component(s):**  
`Frontend`

reported by @Bensk1

**Comment by Bensk1** [comment]
I don't know whether that is correct. There might be some confusion here. What I meant: after adding a database (or multiple databases) it was not possible to open the plugin overlay. This only worked after reloading. I am pretty sure that the frontend guys were aware of this issue.

**Comment by Bensk1** [comment]
I would like to pin this one but there is a maximum of 3 pinned issues.

**Comment by fabianhe** [comment]
Feel free to unpin/pin @Bensk1.

**Comment by MaxSchneider1337** [comment]
> I don't know whether that is correct. There might be some confusion here. What I meant: after adding a database (or multiple databases) it was not possible to open the plugin overlay. This only worked after reloading. I am pretty sure that the frontend guys were aware of this issue.

I already wrote an issue for that, see #402

**Comment by MaxSchneider1337** [comment]
The plugin editor seems to work in about 50% of the cases i tried. I think it has something to do with the endpoint returning `null` in the get plugin_settings endpoint

**Comment by cH3n7i** [comment]
Duplicate closed, closing this as well
