### ISSUE TITLE
Show a running workload indicator 

### ISSUE THREAD

**Issue by cH3n7i** [hyrise/Cockpit#432]
**Is your feature request related to a problem? Please describe:**  
Despite the throughput spike and treemap, there is no indicator whether a workload is running.
In addition it is not visible what workload is currently running.

**Please describe the solution you'd like:**  
The slider / radio button in the workload menu should indicate what workload is currently running.

**Affected Component(s):**  
`Frontend`, `Backend`

reported by @Bensk1

**Comment by Bensk1** [comment]
I would like to pin this one but there is a maximum of 3 pinned issues.

**Comment by kathwill** [comment]
What do you mean by this exactly? Do you want to see that and which workload you started or if and which workload is currently running (so you reloaded or somebody else started a workload)?

**Comment by heseding** [comment]
Should we reopen this or open a separate frontend issue? @cH3n7i
