### ISSUE TITLE
Show compression type in treemap

### ISSUE THREAD

**Issue by cH3n7i** [hyrise/Cockpit#435]
**Please describe the solution you'd like:**  
Show the used compression type in the treemap to improve insights - e.g. Dictionary (FSBA).

**Affected Component(s):**  
`DatabaseManager`, `Cockpit`, `Frontend`

as reported by @Bensk1

**Comment by Bensk1** [comment]
This is @Bouncner's topic, he might add some more information. For the segments, there is not only an encoding type, but also a compression type. You already get both via the meta tables. So the idea is to also display the compression type: EncodingType (CompressionType) or as you showed above Dictionary (FSBA).
