### ISSUE TITLE
Visualize encoding types in percentage

### ISSUE THREAD

**Issue by cH3n7i** [hyrise/Cockpit#436]
**Please describe the solution you'd like:**  
Visualize the used encodings e.g. 60%: Dictionary (FSBA), 40%: LZ4 (SIMDBP128)

**Affected Component(s):**  
`DatabaseManager`, `Cockpit`, `Frontend`

**Additional context:**  
Feel free to add some more description as I can't quite grab it yet, @Bensk1

**Comment by Bensk1** [comment]
This is @Bouncner's topic, he might add some more information. For the segments, there is not only an encoding type, but also a compression type. You already get both via the meta tables. So the idea is to also display the compression type: EncodingType (CompressionType) or as you showed above Dictionary (FSBA).

**Comment by Bensk1** [comment]
Tables consist of multiple chunks. Therefore, a column has multiple segments. Each segment could have a different encoding. Currently, we already show multiple encodings per column but we do not display the distribution. Above's example would, for example, correspond to a table with 10 chunks. For one of its columns, 6 segments would be dictionary encoded, the other 4 with LZ4.
