### ISSUE TITLE
Add a way to remove databases via Frontend

### ISSUE THREAD

**Issue by cH3n7i** [hyrise/Cockpit#437]
**Is your feature request related to a problem? Please describe:**  
Currently a connected database can just be disconnected by calling the API or restarting the Cockpit.

**Please describe the solution you'd like:**  
Add a frontend button to remove connected databases.

**Affected Component(s):**  
`Frontend`

**Additional context:**  
The endpoint is already available, it just has to be implemented from the frontend side of things.

**Comment by schTi** [comment]
already done! :fire:
