### ISSUE TITLE
Add a text field to send SQL-Input

### ISSUE THREAD

**Issue by cH3n7i** [hyrise/Cockpit#443]
**Please describe the solution you'd like:**  
To customize the database manipulation we would like to implement a "custom SQL input" field.
Feel free to add a scenario (if there's already one), @Bensk1 

**Affected Component(s):**  
`DatabaseManager`, `Cockpit`, `Frontend`

**Comment by Bensk1** [comment]
The user of the Cockpit (e.g., DBA) might want to add certain indexes manually.

**Comment by fabianhe** [comment]
There's already a backend issue at #428 for this.
