### ISSUE TITLE
Improve the javascript performance

### ISSUE THREAD

**Issue by cH3n7i** [hyrise/Cockpit#444]
**Is your feature request related to a problem? Please describe:**  
The javascript used in the frontend lacks performance.

**Please describe the solution you'd like:**  
Improve the performance by improving the compiling, minifying or compressing it.
Feel free to add more ideas @Bensk1 

**Affected Component(s):**  
`Frontend`

**Comment by Bensk1** [comment]
I don't know whether this quick analysis tool (or something similar) can also be used for local deployments: https://developers.google.com/speed/pagespeed/insights/

**Comment by MaxSchneider1337** [comment]
Building the app with npm run build starts it in production mode, which already minifies and gzipps it.

Still we should look how we can only import a part of plotly.js

**Comment by MaxSchneider1337** [comment]
> Building the app with npm run build starts it in production mode, which already minifies and gzipps it.
> 
> Still we should look how we can only import a part of plotly.js

https://github.com/plotly/plotly.js/blob/master/dist/README.md#partial-bundles

https://github.com/plotly/plotly.js/#modules
