### ISSUE TITLE
timestamp formatting on small screens

### ISSUE THREAD

**Issue by MaxSchneider1337** [hyrise/Cockpit#457]
**Please describe the bug:**  
timestamp formatting breaks on the overview site

**What is the expected behavior? Please describe:**  
timestamps should have a set breakpoint on "-"

**Comment by schTi** [comment]
Add de-DE as default locale

**Comment by MaxSchneider1337** [comment]
> Add de-DE as default locale
added extra issue for that, since it has to be changed in many places. both issues can still be solved in one pr
