### ISSUE TITLE
improve database distinctness on comparison-screen

### ISSUE THREAD

**Issue by MaxSchneider1337** [hyrise/Cockpit#489]
**Is your feature request related to a problem? Please describe:**  
Databases are hard to differentiate in the comparison screen.
 
**Please describe the solution you'd like:**  
Implement a colored header (should be fixed on top of the screen) and draw a vertical line between db instances.

**Additional context:**  
![image](https://user-images.githubusercontent.com/38442947/78563854-e59dde00-781b-11ea-86a1-c86f089eeaed.png)

Before: (please ignore the long database names for now)
![image](https://user-images.githubusercontent.com/49497676/79337008-06a1b580-7f25-11ea-82b6-888f2deb1a9d.png)

After:
![image](https://user-images.githubusercontent.com/49497676/79443315-f7c90a80-7fd9-11ea-969f-98802a72446c.png)

**Comment by monasobh** [comment]
Please make sure to contact me before working on this issue, because I have already started working on the design of the "Database System Information" panel. So maybe we can discuss this and include it into this issue.
