### ISSUE TITLE
implement precision slider

### ISSUE THREAD

**Issue by MaxSchneider1337** [hyrise/Cockpit#496]
**Is your feature request related to a problem? Please describe:**  
Frontend probably can't show 60 min of linechart-data in real time.

**Please describe the solution you'd like:**  
precision slider to give the backend an interval to aggregate historical data.

**Affected Component(s):**  
Frontend

**Additional context:**  
see salck thread

**Comment by Bouncner** [comment]
I wouldn't call it a precision slider. That can be hardcoded (like at most 100 data points) and does not need to be exposed to the user.
What is more important to me is the ability to select the shown time frame (and if that time frame is too large, we should draw only the part where data points exist).

Does that make sense to you?
