### ISSUE TITLE
Provide metric requests with time precision

### ISSUE THREAD

**Issue by PeterTsayun** [hyrise/Cockpit#497]
**Is your feature request related to a problem? Please describe:**  
After #484, the backend will be able to provide historical data for metrics in 1s time intervals. When requesting a time interval of a big length (like 1 hour), it would cause a transfer of 3600 points over a network for each metric. As we won't plot all 3600 in the graph anyway, we need to make aggregation over a suitable time interval.

**Please describe the solution you'd like:**  
The frontend should be able to provide precision for a time interval, like 1s, 5s, 30s, 1m. The data should be aggregated in the time interval of the provided length.

**Please describe alternatives you've considered:**  
Alternatives are welcome.

**Affected Component(s):**  
`App`, `InfluxDB`

**Additional context:**  
Related to #496.

**Comment by Bouncner** [comment]
Please don’t call that down sampling.
