### ISSUE TITLE
improve metrics naming and design

### ISSUE THREAD

**Issue by MaxSchneider1337** [hyrise/Cockpit#518]
**Is your feature request related to a problem? Please describe:**  
y-axes labels look kind of odd.

**Please describe the solution you'd like:**  
will still need to discuss this, maybe we should show them horizontally. 

**Please describe alternatives you've considered:**
we could also just add the label in the chart-title

- [x] change number formatting from 23'300 to 23 300 (only spaceletter)

**Affected Component(s):**  
Frontend

![image](https://user-images.githubusercontent.com/49497676/81543431-57ff6200-9376-11ea-97f7-c0bf14f997b1.png)

![image](https://user-images.githubusercontent.com/49497676/81543459-60f03380-9376-11ea-8126-7e378c9f7638.png)

![image](https://user-images.githubusercontent.com/49497676/81543485-69486e80-9376-11ea-800e-148002d43f58.png)
change number formatting from 23'300 to 23 300
![image](https://user-images.githubusercontent.com/49497676/81550018-f47a3200-937f-11ea-9388-6f2576fb97c0.png)

**Comment by monasobh** [comment]
Maybe we can also change the font style from bold "Interval: last second" to normal, like Martin suggested in the UI Channel, in this issue?!
