### ISSUE TITLE
Size of metric numbers wont resize when adding many databases

### ISSUE THREAD

**Issue by monasobh** [hyrise/Cockpit#534]
**Please describe the bug:**  
The numbers in the middle of a metric do not respond/resize automatically when you're adding a lot of databases.

**Please describe steps to reproduce:**  
Add databases until the number of q/s will be on the title of the metric.

**What is the expected behavior? Please describe:**  
The size of the numbers should become automatically smaller. Make it responsive.

**Screenshot(s):**  
![image](https://user-images.githubusercontent.com/49497676/79636050-4e1e8080-8175-11ea-88f4-a2756efbb117.png)

**Affected Component(s):**  
`Frontend`

**Comment by Bouncner** [comment]
Should it resize? I’d rather expect to float to the next line below the title.

**Comment by MaxSchneider1337** [comment]
this is already included in #520
