### ISSUE TITLE
Background job scheduler needs refactoring

### ISSUE THREAD

**Issue by Alexander-Dubrawski** [hyrise/Cockpit#568]
**Is your feature request related to a problem? Please describe:**  
At the moment the `BackgroundJobManager` is 577 lines long. The test for this component is 1352 lines long. This component is at the moment, not scalable. 

**Please describe the solution you'd like:**  
We can move all `job` entities in separate files. That way we have a scalable solution.

**Affected Component(s):**  
`BackgroundJObManager`

**Comment by Bouncner** [comment]
What does the number of lines per file has to do with scalability?

**Comment by Alexander-Dubrawski** [comment]
> What does the number of lines per file has to do with scalability?

In general not directly. But it is a code smell. In our case, we have a lot of separated logical components in one file. If the file is getting bigger and bigger it's getting harder to work with it (more conflicts if more than one person is working on the file, it's harder to read, ...). So if we find a clean structure we can implement features faster and more reliable. That's what I meant with scalability.
