### ISSUE TITLE
improve visibility of database warnings

### ISSUE THREAD

**Issue by MaxSchneider1337** [hyrise/Cockpit#583]
**Is your feature request related to a problem? Please describe:**  
It's hard to see the db warnings, when the viewport is scrolled down

**Please describe the solution you'd like:**  
show the warnings as snackbar

**Affected Component(s):**  
Frontend

![image](https://user-images.githubusercontent.com/49497676/81821648-5f6b6a80-9532-11ea-857b-5d3c2c68ba87.png)

**Comment by monasobh** [comment]
What do you think of showing this warning in the navbar and not above the database information boxes? There is still a lot of space and it would be shown while scrolling.
