### ISSUE TITLE
Hyrise crashes when trying to load already existing plugin 

### ISSUE THREAD

**Issue by Alexander-Dubrawski** [hyrise/Cockpit#591]
**Please describe the bug:**  
If we try to load the same plugin twice the hyrise crashes wit the exception: 

![IMAGE 2020-05-06 11:11:17](https://user-images.githubusercontent.com/32880898/81160427-54d93000-8f8a-11ea-998d-36dec50ef323.jpg)

**Please describe steps to reproduce:**  
1. Add a plugin 
2. Add the same plugin again

**Affected Component(s):**  
`DatabaseManager`, `Frontend`, ...

**Additional context:**  
We should check whenever we activate a plugin if it is already activated. We can do this in the frontend or backend.

**Comment by heseding** [comment]
I vote for checking this in the backend.

**Comment by Bouncner** [comment]
Status?

**Comment by Alexander-Dubrawski** [comment]
> Status?

We still need to implement it. I would suggest doing it after #563 is merged.
