### ISSUE TITLE
huge plugin logs

### ISSUE THREAD

**Issue by schTi** [hyrise/Cockpit#605]
**Please describe the bug:**  
The plugin logs make up too much space. When creating this issue the log size is around 1.5 MB, which takes really long to response and is really hard to handle via frontend. This causes performance issues and the logs are still getting bigger over time.

**Please describe steps to reproduce:**  
1. Activate Plugin
2. See growth of plugin logs over time

Another thing I noticed is, that there are many duplicated log entries. E.g.:
![image](https://user-images.githubusercontent.com/49444254/81317175-cf8a7400-908c-11ea-9404-57020c2c7bbb.png)

I do not think its necessary to send the same message every few seconds, because this will blow op the plugin log data.

**Affected Component(s):**  
`DatabaseManager`, `Backend`, ...

**Comment by Bouncner** [comment]
This should be solved by the logging levels. At least part of it (the many boring status messages).

**Comment by Bouncner** [comment]
Has this been solved?

**Comment by heseding** [comment]
@Bouncner This has not been resolved so far.
We want to add a filtered endpoint (e.g. `GET` `/plugin/log/warning`) as suggested in #610.
