### ISSUE TITLE
Add log levels to the plugin log endpoint

### ISSUE THREAD

**Issue by heseding** [hyrise/Cockpit#610]
**Is your feature request related to a problem? Please describe:**  
Related to #605.

**Please describe the solution you'd like:**  
1. Requesting the plugin log at `/plugin_log` should pass only the most important warnings by default. Optionally, a parameter `min_log_level` could be passed (e.g. "show all log messages with level 1 and above").
2. The response should include the log level for each log message in plain text (e.g. `Debug`, `Info`, ...).

**Please describe alternatives you've considered:**  
- Marking the parameter `min_log_level` required, thus breaking the the current interface?
- Adding a parameter `max_log_level`?
- Just using a `log_level` parameter that returns only the specified log level messages?

**Affected Component(s):**  
`CockpitBackend`, `DatabaseManager`

**Additional context:**  
- The endpoint should be ported to the new API structure and tests should be added/adapted.
- Log levels are defined [in Hyrise](https://github.com/hyrise/hyrise/blob/0be3ad615e7b929cd67c5757ce979611bae74174/src/lib/types.hpp#L234).

**Comment by heseding** [comment]
@MaxSchneider1337 @schTi @kathwill @monasobh which filtering behavior would you like?

**Comment by Bouncner** [comment]
Why reopened?

**Comment by heseding** [comment]
@Bouncner The parameter for a filtered endpoint and the tests are not yet done.
#615 did implement some functionality but accidentally closed this.
