### ISSUE TITLE
Change system data endpoint

### ISSUE THREAD

**Issue by heseding** [hyrise/Cockpit#611]
**Is your feature request related to a problem? Please describe:**  
New fields have been added to the [`MetaSystemInformationTable`](https://github.com/hyrise/hyrise/blob/0be3ad615e7b929cd67c5757ce979611bae74174/src/lib/utils/meta_tables/meta_system_information_table.cpp#L16) and [`MetaSystemUtilizationTable`](https://github.com/hyrise/hyrise/blob/0be3ad615e7b929cd67c5757ce979611bae74174/src/lib/utils/meta_tables/meta_system_utilization_table.cpp#L13), thus we do not need to mock some values anymore. Some names have been changed.
Additionally, CPU time is now the total time all CPUs consumed. A relative time can be obtained by dividing the total time with `cpu_count`.

**Please describe the solution you'd like:**  
Return the new fields in the backend endpoint.

**Please describe alternatives you've considered:**  
None.

**Affected Component(s):**  
`DatabaseManager`, `CockpitBackend`

**Comment by cH3n7i** [comment]
As we observe Hyrise Server (build from [branch bp1920](https://github.com/hyrise/hyrise/tree/bp1920) ) failing, the added/removed/changed fields seem to be a strong candidate as the reason.
I'm bumping up the prio to 0 and pin this as we have a serious blocker here.

@Bensk1 @Bouncner feel free to add your wisdom

**Comment by Bensk1** [comment]
As discussed in Slack, we should adapt to the new names first. If problems remain, we can have a more detailed look into it.
