### ISSUE TITLE
global running workload indicator

### ISSUE THREAD

**Issue by kathwill** [hyrise/Cockpit#617]
**Is your feature request related to a problem? Please describe:**  
Currently it is only possible to see if a workload is running when you go to the workload settings dialog.

**Please describe the solution you'd like:**  
Adding the play, pause and stop icon in the navigation bar according to the current status would help the user to see on every page if the workload is running or not without the need of opening the dialog.

**Affected Component(s):**  
`Frontend`

Play-icon as badge will turn from: 
grey to green, once a worklaod has been started
green to blue, once a workload has been paused
green/blue to red, once a workload has been stopped
![image](https://user-images.githubusercontent.com/49497676/81796628-ff62cd00-950d-11ea-93d7-c0f84c4f4396.png)

**Comment by Bouncner** [comment]
I'd expect a clickable button in the first variant. I guess I would think it starts the workload.

So I think the second version is better.

**Comment by monasobh** [comment]
> I'd expect a clickable button in the first variant. I guess I would think it starts the workload.
> 
> So I think the second version is better.

Yes, I agree. Thanks for your feedback.
