### ISSUE TITLE
Unrealistic high cpu usage numbers 

### ISSUE THREAD

**Issue by Alexander-Dubrawski** [hyrise/Cockpit#633]
**Please describe the bug:**  
We are getting unrealistic high values from the `/system` endpoint.  

**Please describe steps to reproduce:**  
1. Add a database.
2. get data from the `/system` endpoint

**What is the expected behavior? Please describe:**  
`cpu_process_usage` and `cpu_system_usage should` be between 0 and 100%.

**Screenshot(s):**  
![IMAGE 2020-05-16 11:48:21](https://user-images.githubusercontent.com/32880898/82116579-266a0a80-976b-11ea-879f-7253bf7d17af.jpg)

**Affected Component(s):**  
`DatabaseManager`

**Additional context:**  
It is interesting to see that the `cpu_process_usage` seems to grow linear even if no workload is running.

![IMAGE 2020-05-16 11:49:47](https://user-images.githubusercontent.com/32880898/82116604-5a453000-976b-11ea-9d1a-1ab64ec8a83c.jpg)

**Comment by Bouncner** [comment]
Whats the status of adapting CPU to the new meta tables? I think we have discussed this this week.
