### ISSUE TITLE
improve operator chart readability

### ISSUE THREAD

**Issue by schTi** [hyrise/Cockpit#661]
**Is your feature request related to a problem? Please describe:**  
Currently its hard to compare the data of the different operator charts.

**Please describe the solution you'd like:**  
Synchronize all colors and show persistent percentages to improve this.

**Affected Component(s):**  
`Frontend`

**Comment by Bouncner** [comment]
I don't know what you mean by "persistent". But in case there is a nice way to show labels within the bars (and plotly manages to skip them for the smallest bars, where they wouldn't fit), please also include the operators name (e.g., "JoinHash 50%" with a popup that also states the runtime etc.).
