### ISSUE TITLE
Unify close buttons

### ISSUE THREAD

**Issue by monasobh** [hyrise/Cockpit#667]
**Is your feature request related to a problem? Please describe:**  
We use different close buttons/options which can be confusing for the user. 

**Please describe the solution you'd like:**  
For more intuitive work we should use the same close buttons everywhere. It won't replace the current close function (pressing the same button will open and close the window), just adds another close option which we already use for other dialogues (e.g. Workload Generation). 

**Affected Component(s):**  
`Frontend`, `UI`

Before: 
<img width="361" alt="Screenshot 2020-07-13 at 18 41 49" src="https://user-images.githubusercontent.com/49497676/87330393-ce683e00-c538-11ea-8d7e-83c2f4bbe691.png">

Changes:
- Added close button (X) 
- Adapted Design (colors) to other dialogues e.g. Workload Generation (same font, size, color etc.)
- Remove Caps Lock for consistent typography
- Changed title from "Comparison" to "Comparison Page Settings". 
- Changed title "Data" to Databases and Metrics

<img width="389" alt="Screenshot 2020-07-14 at 10 36 43" src="https://user-images.githubusercontent.com/49497676/87404080-f6e64b80-c5bd-11ea-9a7c-3306067852e2.png">

<img width="366" alt="Screenshot 2020-07-14 at 10 39 24" src="https://user-images.githubusercontent.com/49497676/87404341-4f1d4d80-c5be-11ea-809a-6028e7b0ff52.png">

Changes: 
- Inserted Remove Icon into DB Button 
- Added "SQL" for better understanding of the Icon
- Added close button (X) 
- Adapted Design (colors) (font, size, color etc.)

<img width="386" alt="Screenshot 2020-07-14 at 16 10 35" src="https://user-images.githubusercontent.com/49497676/87435886-97536480-c5ec-11ea-95d8-f2e47faf3f90.png">

More changes (from left to right): 
<img width="340" alt="Screenshot 2020-07-18 at 10 17 26" src="https://user-images.githubusercontent.com/49497676/87848370-fdd3cd80-c8df-11ea-90ae-d0ac46b5ad42.png">
<img width="340" alt="Screenshot 2020-07-18 at 10 17 34" src="https://user-images.githubusercontent.com/49497676/87848372-00cebe00-c8e0-11ea-8d00-ed5d492ba915.png"><img width="340" alt="Screenshot 2020-07-18 at 11 53 58" src="https://user-images.githubusercontent.com/49497676/87850473-c15c9d80-c8f0-11ea-9107-bc4cb0558a26.png">

<img width="332" alt="Screenshot 2020-07-18 at 12 16 06" src="https://user-images.githubusercontent.com/49497676/87850440-9b36fd80-c8f0-11ea-8057-96a658e0d019.png"><img width="363" alt="Screenshot 2020-07-18 at 12 12 08" src="https://user-images.githubusercontent.com/49497676/87850379-12b85d00-c8f0-11ea-946f-a5c0ed228986.png">

**Comment by monasobh** [comment]
@Bensk1 would you agree with the changes?

**Comment by Bensk1** [comment]
Good job unifying the close buttons, providing proper titles for the windows , and clarifying the SQL interface. A few minor thoughts:

1. Can we increase the space between the icon and `SQL` a little bit? The space left of the icon and right of SQL could be a bit smaller.
1. The + (add button) for databases looks a bit lost
1. I am not sure if I like the trash can icon as part of the database. Maybe we could have second (third) opinion here.

For second opinion @kathwill, @MaxSchneider1337, @schTi.

**Comment by monasobh** [comment]
Alright. I adapted the changes. What do you think about the "Add" Button?
I agree with the trash can, I would also prefer the (X) icon. I just remembered that there was already a discussion between Martin and @schTi. I think the X wasn't "enough" for the meaning of "removing" a database. Is that right, @schTi ??

![databases](https://user-images.githubusercontent.com/49497676/87449332-5adc3480-c5fd-11ea-8a38-9a2439dd5618.png)

**Comment by schTi** [comment]
Yes, the close icon did not indicated, that the removal is persistent. That's why we used the trash can

**Comment by Bensk1** [comment]
I would probably go for the bottom left version. Should such a button be below or on top of the already existing items? 

I was not arguing against the trash can icon but against the way the trash can was displayed in the proposal (also, it wasn't that bad, only a minor thing). If there was already a discussion regarding `X` and trash can, we should stick with it and display it in a good way.

**Comment by schTi** [comment]
Placing the `add`-button as in the above pictures takes up an entire row. In my opinion we are loosing some space here and the button would perfectly fit into the header

**Comment by monasobh** [comment]
Thoughts? @Bensk1 @schTi @kathwill 

<img width="284" alt="Screenshot 2020-07-15 at 11 34 51" src="https://user-images.githubusercontent.com/49497676/87529691-a3dcc900-c68f-11ea-886e-0692a29089fe.png">
<img width="252" alt="Screenshot 2020-07-15 at 11 45 41" src="https://user-images.githubusercontent.com/49497676/87530549-c6231680-c690-11ea-8973-a6a97860c61b.png">

**Comment by Bensk1** [comment]
Looks good to me.

**Comment by kathwill** [comment]
I really like the new solution. I prefer the upper version because the order of icon and text is consistent to the other UI elements in the dialog.

**Comment by monasobh** [comment]
@Bensk1 Just letting you know, that I did two more changes (checkout last two photos in PR description) to unify the close buttons. The detailed view for the treemap and access frequency and the dialogue for adding databases. Please let me know if you agree. Thanks.

**Comment by Bensk1** [comment]
Looks good to me.
