### ISSUE TITLE
Memory capacity and number of cpus in top bar is 0

### ISSUE THREAD

**Issue by kathwill** [hyrise/Cockpit#676]
**Please describe the bug:**  
After adding a database the system data values for Memory Capacity and CPUs of the added database is 0 (in the top bar). After reloading the page the values are updated.

**Please describe steps to reproduce:**  
1. Add a database
2. Go to the Overview or Comparison page
3. Look at Memory Capacity and CPUs for the added database in the top bar

**What is the expected behavior? Please describe:**  
After receiving the values for Memory Capacity and CPUs the values in the top bar should reload.

**Screenshot(s):**  
<img width="612" alt="Screenshot 2020-07-10 at 16 10 01" src="https://user-images.githubusercontent.com/49514526/87163587-dec5b200-c2c7-11ea-9198-90c15f2ed5e6.png">

**Affected Component(s):**  
`Frontend`

**Comment by MaxSchneider1337** [comment]
reloading the site gives the real numbers, this could be important for the solution
