### ISSUE TITLE
Hyrise crashes after activating two plugins

### ISSUE THREAD

**Issue by kathwill** [hyrise/Cockpit#677]
**Please describe the bug:**  
After activating a plugin on a database instance where another plugin is already activated, the database instance crashes.

**Please describe steps to reproduce:**  
1. Activate a plugin for a database instance
2. Activate another plugin for the same database instance
3. See error

**What is the expected behavior? Please describe:**  
It should either not be possible to activate two plugins or the database instance should not crash.

**Comment by Bensk1** [comment]
Should be fixed in the new version of the BP's HyriseBranch, Commit #a74d1e630e53
