### ISSUE TITLE
Improve equalizer

### ISSUE THREAD

**Issue by kathwill** [hyrise/Cockpit#690]
**Is your feature request related to a problem? Please describe:**  
The tab for the equalizer is not self descriptive. The name and the numbers are not easy to understand.

**Please describe the solution you'd like:**  
Some changes improve the comprehensibility of the equalizer
- [ ] Change the name "Equalizer" (@Bensk1, @Bouncner: What is a good name for the "Equalizer"?)
- [ ] Add explanations for the meaning of the numbers (querie numbers and weights)

**Affected Component(s):**  
`Frontend`

**Additional context:**  
<img width="904" alt="MultipleWorkloads3" src="https://user-images.githubusercontent.com/49514526/87450304-a0e5c800-c5fe-11ea-8327-6e67314b589f.png">

**Comment by Bensk1** [comment]
Hm, `Query Weights`, `Query Proportions`?

**Comment by Bouncner** [comment]
Query weights sound ok to me. No better idea from my side.
