### ISSUE TITLE
Add pre-selection for heatmap

### ISSUE THREAD

**Issue by kathwill** [hyrise/Cockpit#692]
**Is your feature request related to a problem? Please describe:**  
Currently there is no table pre-selected in the heatmap ("Segment Access Frequencies"). That is why a new user notices the metric not as much as the other metrics.

**Please describe the solution you'd like:**  
This can be solved by pre-selecting the biggest table in the heatmap.

**Affected Component(s):**  
`Frontend`

**Additional context:**  
<img width="576" alt="Heatmap" src="https://user-images.githubusercontent.com/49514526/87453978-a396ec00-c603-11ea-8234-14b73a11e41c.png">

**Comment by Bouncner** [comment]
I am fine with the largest table. Would “most often accessedl” table also be possible without a major implementation effort?

**Comment by schTi** [comment]
Yes that should be possible
