### ISSUE TITLE
Add and improve tooltips

### ISSUE THREAD

**Issue by kathwill** [hyrise/Cockpit#693]
**Is your feature request related to a problem? Please describe:**  
Currently the usage of tooltips is not consistent. Moreover, some tooltips only show the text that is already shown (in the element the tooltip belongs to) and are not consistent 

**Please describe the solution you'd like:**  
For a better user guidance new tooltips should be added and the existing tooltips should be improved. Adding tooltips is relevant for functionality that is not explained yet (like the settings button for the Overview, Comparison and Workload Analysis page). Improving existing tooltips should focus on the following:
- The text of the element and the text of the tooltip should differ (see below).
- If a UI element consists of an icon and a text, the tooltip should be shown for the icon and the text (This behavior can be found in the settings window for the Overview, Comparison and Workload Analysis page, e.g. when choosing which metrics to show).

**Affected Component(s):**  
`Frontend`

**Additional context:**  
<img width="236" alt="Tooltips" src="https://user-images.githubusercontent.com/49514526/87455996-9af3e500-c606-11ea-9a3b-37806f9e6e1b.png">

**Comment by monasobh** [comment]
Removed: 
- all tooltips on the coloured round database names 
<img width="234" alt="Screenshot 2020-07-30 at 11 07 24" src="https://user-images.githubusercontent.com/49497676/88905849-0d93d000-d257-11ea-8efb-a0cfade9be9a.png">

- tooltips on metrics to show or hide
<img width="244" alt="Screenshot 2020-07-30 at 11 07 19" src="https://user-images.githubusercontent.com/49497676/88905847-0c62a300-d257-11ea-80cf-3c6a613eb3fc.png">

- tooltip for setting the time (unnecessary with new design for setting time range, see #684)
<img width="231" alt="Screenshot 2020-07-30 at 11 28 38" src="https://user-images.githubusercontent.com/49497676/88906643-f7d2da80-d257-11ea-81da-9e37d8692a03.png">

**Comment by kathwill** [comment]
Added: 
- on the navigation bar
<img width="476" alt="AddTooltips1" src="https://user-images.githubusercontent.com/49514526/88929312-43967b80-d27a-11ea-9fa8-30db4a6f765e.png">
<img width="293" alt="AddTooltips3" src="https://user-images.githubusercontent.com/49514526/88929318-45603f00-d27a-11ea-8787-3ade4def84bd.png">

- in the "Add new database"-dialog
<img width="503" alt="AddTooltips2" src="https://user-images.githubusercontent.com/49514526/88929315-44c7a880-d27a-11ea-89b1-55a483aea9b9.png">

- in the "Workload Settings"-dialog
<img width="281" alt="AddTooltips4" src="https://user-images.githubusercontent.com/49514526/88929321-45f8d580-d27a-11ea-89a9-2615c19bfe37.png">
<img width="279" alt="AddTooltips5" src="https://user-images.githubusercontent.com/49514526/88929323-46916c00-d27a-11ea-86ac-1c093fd50139.png">
<img width="388" alt="AddTooltips6" src="https://user-images.githubusercontent.com/49514526/88929325-472a0280-d27a-11ea-8b82-9130c7a2b5bf.png">
<img width="405" alt="AddTooltips7" src="https://user-images.githubusercontent.com/49514526/88929326-47c29900-d27a-11ea-8d75-72c77cc32b18.png">

**Comment by monasobh** [comment]
@Bensk1 Do you agree with the removed/added tooltips?

**Comment by Bensk1** [comment]
Works for me!
