### ISSUE TITLE
Adapt design of workload analysis page 

### ISSUE THREAD

**Issue by monasobh** [hyrise/Cockpit#703]
**Is your feature request related to a problem? Please describe:**  
The Workload Analysis page is not similar to the design of other pages. 

**Please describe the solution you'd like:**  
This page should look similar to the other pages. "Query Information" should be a title for the database columns. 

**Affected Component(s):**  
`UI`, `Frontend`,

Before: 
<img width="639" alt="Screenshot 2020-07-17 at 23 28 42" src="https://user-images.githubusercontent.com/49497676/87832250-dd772500-c885-11ea-829e-f26a58eb2e38.png">
<img width="640" alt="Screenshot 2020-07-17 at 23 35 04" src="https://user-images.githubusercontent.com/49497676/87832377-2929ce80-c886-11ea-9248-ae89f5192ac3.png">

After changes: 
<img width="740" alt="Screenshot 2020-07-27 at 10 16 40" src="https://user-images.githubusercontent.com/49497676/88519464-70d0f880-cff2-11ea-9e70-7115a4567b34.png">

**Comment by monasobh** [comment]
@Bensk1 @Bouncner What do you think of inserting the Query Information for each DB into the DB columns? I think it would add a universal look. Or was there a reason to separate it?

**Comment by Bensk1** [comment]
I don't really understand what you mean. The first screenshot does not contain any stacked bar charts.

**Comment by Bouncner** [comment]
I guess I am missing the last weeks discussions. Can we elaborate a bit?

**Comment by monasobh** [comment]
Currently the database query information table is outside of the coloured database column, which will appear right after the query information table (screenshot two) once you scroll down the page. My suggestion would be to insert the database query information table into the coloured database column. 

<img width="840" alt="Screenshot 2020-07-20 at 12 02 30" src="https://user-images.githubusercontent.com/49497676/87926316-d0268a00-ca81-11ea-9b99-86acd6c91a7b.png">

**Comment by Bouncner** [comment]
Sounds good.

**Comment by Bouncner** [comment]
And haven't we found other names than "statement proportions"? Not sure, but I know there was some discussion about that. :-/

**Comment by Bouncner** [comment]
Ah, found it. It was another discussion with Petr, but more about the API naming.

Still, we can find a better name there. (not part of this issue here)

**Comment by monasobh** [comment]
@Bensk1 @Bouncner Please check the photo of the new design in the description above. What should be the content of the details header bar? Just the database name (as it is right now) or the database details information similar to the comparison page, like this: 
<img width="840" alt="Screenshot 2020-07-27 at 10 25 43" src="https://user-images.githubusercontent.com/49497676/88520218-8c88ce80-cff3-11ea-9b82-d7f401f1e0a2.png">

**Comment by Bensk1** [comment]
Hm, I think we don't necessarily need all the information for this view. But if the header has the same size as in the comparison view and the space is unused (as in the description's picture), we can also make use of it. 

Also, do we need the round colored button below the header that shows the database name again?

**Comment by monasobh** [comment]
>Hm, I think we don't necessarily need all the information for this view. But if the header has the same size as in the comparison view and the space is unused (as in the description's picture), we can also make use of it.

The header can also be small, if the information is not needed. (And then without the round coloured db name I could put the "Search Queries" next to the header. ) 
<img width="740" alt="Screenshot 2020-07-28 at 09 13 19" src="https://user-images.githubusercontent.com/49497676/88631534-9cb3b300-d0b2-11ea-8aa7-37c159a3795d.png">

>Also, do we need the round coloured button below the header that shows the database name again?

Do you mean in general, also on the comparison page or just here on the workload analysis page? For the comparison page, I think we sticked to it because it's helpful to always see the db name, no matter where on the page you are. e.g. if you don't see the header, you would have to scroll up. Although we have some tooltips (see photo below), which might be enough. 
<img width="740" alt="Screenshot 2020-07-28 at 09 08 11" src="https://user-images.githubusercontent.com/49497676/88631106-eb148200-d0b1-11ea-9050-016fc6d721cc.png">

**Comment by Bensk1** [comment]
> The header can also be small, if the information is not needed. (And then without the round coloured db name I could put the "Search Queries" next to the header. )

That would be fine for me.


> Do you mean in general, also on the comparison page or just here on the workload analysis page? For the comparison page, I think we sticked to it because it's helpful to always see the db name, no matter where on the page you are. e.g. if you don't see the header, you would have to scroll up. 

Let's stick with it then.
