### ISSUE TITLE
Workload Settings are disabled

### ISSUE THREAD

**Issue by kathwill** [hyrise/Cockpit#707]
**Please describe the bug:**  
After adding a database for the first time, the "Workload Settings" dialog is sometimes disabled. Reloading the site solves the problem. It is possible that the value for available databases it not updated correctly.

**Please describe steps to reproduce:**  
1. Add the first database
2. Click on "Workload Settings"
3. See error

**What is the expected behavior? Please describe:**  
After adding a database, it should be possible to load and start a workload in the "Workload Settings".

**Screenshot(s):**  
<img width="903" alt="BugWorkloadSettingsDisabled" src="https://user-images.githubusercontent.com/49514526/87941065-daa14d80-ca9a-11ea-8ddb-555b1a10fa89.png">

**Affected Component(s):**  
`Frontend`

**Comment by schTi** [comment]
Looks like there is missing an `{immediate: true}` on some watcher

**Comment by kathwill** [comment]
> Looks like there is missing an `{immediate: true}` on some watcher

This problem already existed before the update of the dependencies. Do you still think that this is the problem?

**Comment by schTi** [comment]
Nope, this doesnt matter then

**Comment by kathwill** [comment]
I was not able to reproduce this bug with the current dev version.
