### ISSUE TITLE
Cannot add a database in frontend

### ISSUE THREAD

**Issue by Alexander-Dubrawski** [hyrise/Cockpit#716]
**Please describe the bug:**  
I am not able to add a database in the frontend. I installed and started the frontend as follows: 
1. npm install
2. npm run build
3. npm run deploy

**Please describe steps to reproduce:**  
1. open frontend.
2. Click on add database
3. add database
4. nothing happens 

**What is the expected behavior? Please describe:**  
There should be a database added 

**Affected Component(s):**  
`fronent`

**Additional context:**  
I tested the backend separately and there everything is working fine. In the developer console of my chrome browser, I wasn't seeing a request that was leaving the frontend. I checked my .env files and everything was set correctly.

**Comment by MaxSchneider1337** [comment]
I was not able to reconstruct this issue. Could you show me the requests the frontend sends to the backend(should be one to add the database and another one to get the currently running databases)?

**Comment by heseding** [comment]
Is this still an issue or can this be closed? Does anyone else run into this?

**Comment by Bouncner** [comment]
I cannot add databases when I am using a freshly installed instance using Docker.

So the issue appears to still exist.

**Comment by Bouncner** [comment]
I tried to see the requests going out but there are no request when I click on "save" (why is it save anyways and not add?)

**Comment by Bouncner** [comment]
Just to keep that issue here up to date: there is a long discussion in Slack. Udo and me played around a lot and it appears to be an issue not just for Docker-based setups. A request is send, but nothing happens. Works when the request is sent via Swagger.

**Comment by schTi** [comment]
Closing this, because this was caused by a wrong host name, which should be fixed now

**Comment by Bouncner** [comment]
What PR fixed it?

**Comment by Bouncner** [comment]
Cannot add a database. The log of the backend shows the following: `ModuleNotFoundError: No module named 'hyrisecockpit.drivers'`

**Comment by schTi** [comment]
Just to make this clear. In general it's not a problem about adding a database. Because it's the first action you want to do when opening the application, it's the first thing what crashes. But in fact there is (possibly) a deeper problem in the application itself

**Comment by Bouncner** [comment]
Well, at least for the data loading I'd say it was a frontend bug if the front end does not even say that an error occurred. :)

But I see your point and I am aware that the issues lie a little bit deeper down the project. I simply don't want to open drölf issues for such things.

**Comment by Alexander-Dubrawski** [comment]
The problem was fixed by adding init files to all modules. Moreover, in #747, #750, and #748, the deployment was adjusted so that the environment variable is bound correctly for every setup.
