### ISSUE TITLE
Provide guide about drivers

### ISSUE THREAD

**Issue by PeterTsayun** [hyrise/Cockpit#739]
**Is your feature request related to a problem? Please describe:**  
Since #668, we give the users the opportunity to define their own workloads by defining their own drivers. For that purpose, a guide about interfaces that need to be implemented could be helpful.

**Please describe the solution you'd like:**  
Provide a guide about defining of the custom drivers.

**Please describe alternatives you've considered:**  
Alternatives are welcome.

**Affected Component(s):**  
`Documentation`

**Comment by Alexander-Dubrawski** [comment]
Added in the wiki under https://github.com/hyrise/Cockpit/wiki/Implementing-a-Driver
